### ISSUE TITLE
Add an option to remove ALL Gapps.

### ISSUE THREAD

**Issue by MDTech-us-MAN** [CHEF-KOCH/Remove-Gapps#5]
Hello,

Is it possible to add an option to COMPLETELY remove Gapps? My current gapps installation is broken so I need to delete it completely and reinstall.

Thanks.

P.S. I already tried to install a new OpenGapps over my existing install. No results.

**Comment by CHEF-KOCH** [comment]
Usually, the script should remove every Gapps leftovers but without getting more details it's difficult to understand what you#re referring too. 

If you would provide a log or information what doesn't get removed after executing the script I could add your findings, but without information, it's _difficult_ to do something.

**Comment by MDTech-us-MAN** [comment]
I am referring to this passage from the README:
> except CoreGms.apk and Webview [cause they're important])

I would like to remove ALL google components.

**Comment by CHEF-KOCH** [comment]
Webview will not be removed (except the Google own created version) since every Browser and other apps are depending on it, there is also no alternative for it. The Privacy Browser developer said he might work on a fork for it but it's only for his Browser.

CoreGMS will also not removed cause it causes bootloops with Huawaei. The app also should never be removed cause its a collection of Google applications and APIs that help support functionality across devices, YouTube needs. The main reason why it not gets removed is that it [triggers the certification status of your Android](https://support.google.com/googleplay/answer/7165974). [Installing Google Play Store or Goole apps on an uncertified device is against ToS](https://productforums.google.com/forum/#!topic/play/LyyTetNj6_w) and I not risking to get a punishment for this. 

If you want truly Gapps free device install [LineageOS](https://www.lineageos.org/) with [NanoDroid](https://forum.xda-developers.com/apps/magisk/module-nanomod-5-0-20170405-microg-t3584928).

**Comment by MDTech-us-MAN** [comment]
I am ALREADY on LineageOS. The problem is that after an update all of the Gapps stopped working correctly. I am getting errors such as [this](https://stackoverflow.com/questions/46068648/how-to-resolve-security-exception-from-gservices) from GOOGLE apps that used to work right. This tells me that it's a problem communicating with the core google services. 

If you don't want to add an extra option with a disclaimer, can you at least tell me where the files for coregms are?

**Comment by CHEF-KOCH** [comment]
If you used the [opengapps](https://opengapps.org) package then it usually takes care of it since every opengapps package contains and it's own gapps removal script (gapps-remove.txt). 

You can open the package and look for yourself where the apps are located at. 

Usually there only two places, system/app or for background (system apps) /system/priv-app/.

```bash
/system/priv-app/GmsCore
/system/app/PrebuiltGmsCore
```

If you're on lineageos just use the opengapps package and flash it now once, clean dalvik cache, reboot again into TWRP and re-flash it, clean dalvik again and reboot, which solves the problems.
